version: "3"

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  a2billing_rest_api:
    image: maxkonin/a2billing_rest_api:release
    container_name: a2billing_rest_api
    environment:
      HOST: example.com
      PORT: 4000
      MYSQL_USER: root
      MYSQL_PWD: password
      MYSQL_DATABASE: a2billing_rest_api
      MYSQL_HOST: mysql
    depends_on:
      - mysql
