FROM elixir:1.4.2
ENV DEBIAN_FRONTEND=noninteractive
EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash
WORKDIR /app
COPY ./a2billing_rest_api.tar.gz ./
RUN tar xfz a2billing_rest_api.tar.gz
ENTRYPOINT ["bin/a2billing_rest_api", "foreground"]
