use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :a2billing_rest_api, A2billingRestApi.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: System.get_env("HOST"), port: System.get_env("PORT")],
  cache_static_manifest: "priv/static/manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure your database
config :a2billing_rest_api, A2billingRestApi.Repo,
  adapter: Ecto.Adapters.MySQL,
  username: System.get_env("MYSQL_USER"),
  password: System.get_env("MYSQL_PWD"),
  database: System.get_env("MYSQL_DATABASE"),
  hostname: System.get_env("MYSQL_HOST"),
  pool_size: 10
